#pragma once

#define BOARD_TUD_RHPORT 0
#define CFG_TUD_ENABLED 1
#define CFG_TUD_MAX_SPEED OPT_MODE_FULL_SPEED
#define CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_NCM 1
#define CFG_TUD_ECM_RNDIS 0
#define CFG_TUD_CDC 1
#define CFG_TUD_HID 2
#define CFG_TUD_MSC 0
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0
#define CFG_TUD_NET_MTU 1514
#define CFG_TUD_NCM_IN_NTB_MAX_SIZE 2048
#define CFG_TUD_NCM_OUT_NTB_MAX_SIZE 4096
#define CFG_TUD_NCM_IN_NTB_N 1
#define CFG_TUD_NCM_OUT_NTB_N 1
#define CFG_TUD_NCM_DEFAULT_LINK_UP 1
#define CFG_TUD_CDC_RX_BUFSIZE 256
#define CFG_TUD_CDC_TX_BUFSIZE 256
#define CFG_TUD_CDC_EP_BUFSIZE 64
#define CFG_TUD_HID_EP_BUFSIZE 8
#define LWIP_HIGH_THROUGHPUT 1
