"""Generate standard lwIP fsdata (HTTP headers included) from Configurator assets.

No downloads or third-party Python dependencies. Output is a build artifact,
included by lwIP fs.c through HTTPD_FSDATA_FILE, not compiled separately.
"""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
ASSETS = {
    "index.html": "text/html; charset=utf-8",
    "app.js": "application/javascript; charset=utf-8",
    "shortcuts.js": "application/javascript; charset=utf-8",
    "style.css": "text/css; charset=utf-8",
}


def generate():
    lines = ['/* Generated by tools/generate_http_fsdata.py; do not edit. */',
             '#include "lwip/apps/fs.h"']
    previous = 'NULL'
    for index, (name, mime) in enumerate(ASSETS.items()):
        body = (ROOT / 'configurator' / name).read_bytes()
        header = (f'HTTP/1.0 200 OK\r\nContent-Type: {mime}\r\n'
                  f'Cache-Control: no-store\r\nX-Content-Type-Options: nosniff\r\n'
                  f'Content-Length: {len(body)}\r\n\r\n').encode('ascii')
        wire = header + body
        lines.append(f'static const unsigned char data_{index}[] = {{')
        for offset in range(0, len(wire), 24):
            lines.append('  ' + ','.join(str(b) for b in wire[offset:offset + 24]) + ',')
        lines.append('};')
        lines.append(f'static const struct fsdata_file file_{index} = {{ {previous}, '
                     f'(const unsigned char *)"/{name}", data_{index}, sizeof(data_{index}), FS_FILE_FLAGS_HEADER_INCLUDED }};')
        previous = f'&file_{index}'
    # / resolves through lwIP's standard index.html lookup; explicit alias helps other callers too.
    lines.append(f'static const struct fsdata_file root_file = {{ {previous}, '
                 '(const unsigned char *)"/", data_0, sizeof(data_0), FS_FILE_FLAGS_HEADER_INCLUDED };')
    lines.extend(['#define FS_ROOT (&root_file)', '#define FS_NUMFILES 5', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(), encoding='ascii', newline='\n')
